<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net481</TargetFramework>
		<LangVersion>5</LangVersion>
		<UseWindowsForms>true</UseWindowsForms>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
		<TerrariaPath>C:\Program Files (x86)\Steam\steamapps\common\Terraria</TerrariaPath>
		<Platforms>x86</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<OutputPath>bin\Debug\</OutputPath>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<OutputPath>bin\Release\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Microsoft.Xna.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86" />
		<Reference Include="Microsoft.Xna.Framework.Game, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86" />
		<Reference Include="Microsoft.Xna.Framework.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86" />
		<Reference Include="Terraria">
			<HintPath>$(TerrariaPath)\Terraria.exe</HintPath>
		</Reference>
		<Reference Include="ReLogic">
			<HintPath>$(TerrariaPath)\ReLogic.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Include="app.config" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PluginLoader.XNA\PluginLoader.XNA.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
		<PackageReference Include="Krafs.Publicizer" Version="1.0.1" />
	</ItemGroup>

	<ItemGroup>
		<Publicize Include="Terraria;ReLogic" />
	</ItemGroup>

</Project>