<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net481</TargetFramework>
		<PlatformTarget>x86</PlatformTarget>
		<UseWindowsForms>true</UseWindowsForms>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
		<TerrariaPath>C:\Program Files (x86)\Steam\steamapps\common\Terraria</TerrariaPath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Microsoft.Xna.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86" />
		<Reference Include="Microsoft.Xna.Framework.Game, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86" />
		<Reference Include="Microsoft.Xna.Framework.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86" />
		<Reference Include="Terraria">
			<HintPath>$(TerrariaPath)\Terraria.exe</HintPath>
		</Reference>
	</ItemGroup>

</Project>