<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net481</TargetFramework>
		<PlatformTarget>x86</PlatformTarget>
		<Prefer32Bit>false</Prefer32Bit>
		<UseWindowsForms>true</UseWindowsForms>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<ApplicationIcon>Terraria.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Configurations>Debug;Release;Release (Public)</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release (Public)' ">
		<DefineConstants>$(DefineConstants);PUBLIC</DefineConstants>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="CopyPlugins.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Include="CopyPlugins.Designer.cs">
			<DependentUpon>CopyPlugins.cs</DependentUpon>
		</Compile>
		<Compile Include="IL.cs" />
		<Compile Include="Main.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Include="Main.Designer.cs">
			<DependentUpon>Main.cs</DependentUpon>
		</Compile>
		<Compile Include="MyAssemblyResolver.cs" />
		<Compile Include="Program.cs" />
		<Compile Include="Terraria.cs" />
		<Compile Include="Properties\AssemblyInfo.cs" />
		<Compile Include="Properties\Resources.Designer.cs">
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
			<DesignTime>True</DesignTime>
		</Compile>
		<Compile Include="Properties\Settings.Designer.cs">
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="CopyPlugins.resx">
			<DependentUpon>CopyPlugins.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Include="Main.resx">
			<DependentUpon>Main.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Include="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
			<SubType>Designer</SubType>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Include="App.config" />
		<None Include="app.manifest" />
		<None Include="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
		<Content Include="Terraria.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mono.Cecil" Version="0.11.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PluginLoader.XNA\PluginLoader.XNA.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<PostBuildEvent>
			IF "$(Configuration)" == "Debug" EXIT
			if "$(Configuration)" == "Release" SET zip=$(ProjectDir)TerrariaPatcher.zip
			if "$(Configuration)" == "Release (Public)" SET zip=$(ProjectDir)TerrariaPatcher.public.zip
			IF EXIST "%25zip%25" DEL "%25zip%25"
			"C:\Program Files\WinRAR\WINRAR.exe" a -ep1 "%25zip%25" "$(TargetDir)TerrariaPatcher.exe" "$(TargetDir)PluginLoader.XNA.dll" "$(TargetDir)Mono.Cecil.dll" "$(TargetDir)Mono.Cecil.Rocks.dll" "$(TargetDir)TerrariaPatcher.exe.config" "$(ProjectDir)changelog.txt"
			"C:\Program Files\WinRAR\WINRAR.exe" a -ep1 -apPlugins "%25zip%25" "$(ProjectDir)\TranscendPlugins\*.cs"
			"C:\Program Files\WinRAR\WINRAR.exe" a -ep1 -r -apPlugins\Shared "%25zip%25" "$(ProjectDir)\TranscendPlugins\Shared\*.cs"
		</PostBuildEvent>
	</PropertyGroup>

</Project>